// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlUjtlQuYB9uaQeWbx0Zp6zhzwt8XncRY',
    appId: '1:839209705389:web:180c1d3381a4cd83b9cb24',
    messagingSenderId: '839209705389',
    projectId: 'tourist-guide-81f59',
    authDomain: 'tourist-guide-81f59.firebaseapp.com',
    storageBucket: 'tourist-guide-81f59.firebasestorage.app',
    measurementId: 'G-R60P9YFCQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqEmvnvjQHw6P5vjyapvPYc7V63Qmfl3Y',
    appId: '1:839209705389:android:7d97ed44d1b663b9b9cb24',
    messagingSenderId: '839209705389',
    projectId: 'tourist-guide-81f59',
    storageBucket: 'tourist-guide-81f59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoSDzCUVX1g9ylIDEPRRoArpMZVob694Q',
    appId: '1:839209705389:ios:5fd224e8b5d6e26bb9cb24',
    messagingSenderId: '839209705389',
    projectId: 'tourist-guide-81f59',
    storageBucket: 'tourist-guide-81f59.firebasestorage.app',
    iosBundleId: 'com.example.egyptTouristGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoSDzCUVX1g9ylIDEPRRoArpMZVob694Q',
    appId: '1:839209705389:ios:5fd224e8b5d6e26bb9cb24',
    messagingSenderId: '839209705389',
    projectId: 'tourist-guide-81f59',
    storageBucket: 'tourist-guide-81f59.firebasestorage.app',
    iosBundleId: 'com.example.egyptTouristGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlUjtlQuYB9uaQeWbx0Zp6zhzwt8XncRY',
    appId: '1:839209705389:web:065afb60cf4a7ca7b9cb24',
    messagingSenderId: '839209705389',
    projectId: 'tourist-guide-81f59',
    authDomain: 'tourist-guide-81f59.firebaseapp.com',
    storageBucket: 'tourist-guide-81f59.firebasestorage.app',
    measurementId: 'G-C2PXQ5BX2N',
  );
}
